Add solution to all 5 tasks
js-tasks-ru/jsbasic-20210621_deman4ig pull request #2
Opened 2021-06-26 01:03 UTC by Deman4ig

2021-06-26 01:04 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-27 12:43 UTC, SinimaWath requested changes

2021-06-27 12:43 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  for (let word of spamList) {
Все таки, стоит лучше обьявлять переменную word через const, ты же не собираешься ее изменять => значит это const

2021-06-27 12:43 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  return result;
Такую запись можно сократить без промежуточной перемнной и сразу вернуть значение: `return ....`

2021-06-27 12:43 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  const result = (str.length <= maxlength) ? str : `${str.slice(0, maxlength - 1)}…`;
Тут не нужны скобки, в тернарном операторе, сначала выполниться условие: `str.length <= maxlength ? ... : ...`

2021-06-28 16:36 UTC, Deman4ig commented on 1-module/4-task/index.js
> +  for (let word of spamList) {
согласен! написал по принципу for (let i = ...)

2021-06-28 16:36 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-28 16:36 UTC, Deman4ig commented on 1-module/5-task/index.js
> +  return result;
пофиксил

2021-06-28 16:36 UTC, Deman4ig commented on 1-module/5-task/index.js
> +  const result = (str.length <= maxlength) ? str : `${str.slice(0, maxlength - 1)}…`;
и тут тоже пофиксил

2021-06-28 19:03 UTC, SinimaWath approved these changes

2021-06-28 19:04 UTC, merged