Add solutions for all 3 tasks from lessong 6
js-tasks-ru/jsbasic-20210621_deman4ig pull request #6
Opened 2021-07-23 02:09 UTC by Deman4ig

Привет!

Надеюсь не слишком плохо:) т.к. не покидает чувство что можно сделать проще, но нет опыта и мозгов для этого:)

2021-07-23 02:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-23 13:26 UTC, SinimaWath requested changes
Крутое решение, давай поправим маленькие замечания

2021-07-23 13:26 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    return this._table;
А зачем это функци возвращает this._table? У тебя этот код не используется, так что нет смысла здесь возвращать значение

2021-07-23 13:26 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    if (!target.closest('tr')) {
В твоем коде target.closest('tr') вызывается 2 раза. Давай сохраним результат операции в переменную, что бы не делать лишний вызов

2021-07-23 13:26 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this._tbody.append(...rows.map(row => this._generateSingleRow(row)));
круто что использовал spread

2021-07-23 13:26 UTC, SinimaWath commented on 6-module/3-task/index.js
> +import formatPrice from '../../assets/lib/format-price.js';
круто!

2021-07-23 13:26 UTC, SinimaWath commented on 6-module/3-task/index.js
> +      return product.elem;
можно прямо: `return `new CarouselSlide(slide).elem`

2021-07-23 21:52 UTC, Deman4ig commented on 6-module/1-task/index.js
> +    this._tbody.append(...rows.map(row => this._generateSingleRow(row)));
пасиб!

2021-07-23 21:52 UTC, Deman4ig commented on 6-module/3-task/index.js
> +import formatPrice from '../../assets/lib/format-price.js';
пасиб!

2021-07-23 21:58 UTC, Deman4ig commented on 6-module/3-task/index.js
> +      return product.elem;
не знал что из new можно вернуть что то через точку!

2021-07-23 21:59 UTC, Deman4ig commented on 6-module/1-task/index.js
> +    return this._table;
согласен!

2021-07-23 22:01 UTC, Deman4ig commented on 6-module/1-task/index.js
> +    if (!target.closest('tr')) {
поправил!

2021-07-23 22:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-24 15:24 UTC, SinimaWath approved these changes

2021-07-24 15:24 UTC, merged