Add solution for all 4 tasks
js-tasks-ru/jsbasic-20210621_deman4ig pull request #7
Opened 2021-07-29 01:47 UTC by Deman4ig

 Привет!

Вроде сделал.. Слайдер конечно заставил поплакать:)

2021-07-29 01:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-29 16:41 UTC, SinimaWath requested changes

2021-07-29 16:41 UTC, SinimaWath commented on 7-module/1-task/index.css
> +  /*height: 100%;*/
Не уверен, это-то что тебе нужно править :)

2021-07-29 16:41 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    setTimeout(() => {
немного не понимаю зачем тут setTimeout - просто попробовать?

2021-07-29 16:41 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    document.body.addEventListener('keydown', this._closeOnEsc);
Тут тоже надо очищать keydown, иначе на каждый open, создается подписка, но не удаляется

2021-07-29 20:11 UTC, Deman4ig commented on 7-module/1-task/index.css
> +  /*height: 100%;*/
На самом деле с этой высотой у меня неправильно лента отображается

<img width="1366" alt="Screen Shot 2021-07-29 at 4 08 44 PM" src="https://user-images.githubusercontent.com/13958183/127559238-48106aec-d99c-4098-9b28-4884ea8d9c07.png">

но это конечно не имеет отношения к коду:)

2021-07-29 20:30 UTC, Deman4ig commented on 7-module/1-task/index.js
> +    setTimeout(() => {
в задании говорилось что надо скрывать кнопки когда сам скролл закончился.. тк скролл асинхронный и поэтому добавил таймаут.. лучше ничего в голову не пришло:)

2021-07-29 20:33 UTC, Deman4ig commented on 7-module/2-task/index.js
> +    document.body.addEventListener('keydown', this._closeOnEsc);
согласен! в слайдере уже понял что надо удалять:)

2021-07-29 20:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-29 21:59 UTC, SinimaWath requested changes

2021-07-29 21:59 UTC, SinimaWath commented on 7-module/1-task/index.js
> +  _ribbonInner;
Надо задать значение по-умолчанию свойствам

2021-07-29 21:59 UTC, SinimaWath commented on 7-module/3-task/index.js
> +  }
Тебе тут не нужен временный div.
Сейчас ты делаешь так: html -> div -> html.

Можно просто сразу строку формировать без временного div
 Попробуй через map + join

2021-07-29 21:59 UTC, SinimaWath commented on 7-module/3-task/index.js
> +  _segments;
все таки лучше явно задавать значения по-умолчанию

2021-07-29 21:59 UTC, SinimaWath commented on 7-module/3-task/index.js
> +    this._slider.querySelector(`.slider__steps > span:nth-of-type(${value + 1})`).classList.add('slider__step-active');
Тут понятней будет querySelectorAll и брать по индексу

2021-08-03 00:05 UTC, Deman4ig commented on 7-module/3-task/index.js
> +  _segments;
Пересмотрел видео, где ты рассказывал про классы и поставил `prop = null`

2021-08-03 00:05 UTC, Deman4ig commented on 7-module/1-task/index.js
> +  _ribbonInner;
Пересмотрел видео, где ты рассказывал про классы и поставил `prop = null`

2021-08-03 00:06 UTC, Deman4ig commented on 7-module/3-task/index.js
> +    this._slider.querySelector(`.slider__steps > span:nth-of-type(${value + 1})`).classList.add('slider__step-active');
была такая мысль изначально, но подумал что может с точки зрения использования памяти найти конкретный див оптимальнее чем сложить массив в переменную?

Попробовал сделать через массив.

2021-08-03 00:07 UTC, Deman4ig commented on 7-module/3-task/index.js
> +  }
Согласен с первой частью коммента, но не уверен что моя реализация через map + join это то что ты имел ввиду

2021-08-03 00:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-08-03 16:58 UTC, SinimaWath approved these changes
Все круто :)

2021-08-03 16:59 UTC, merged